[package]
name = "spiceware"
version = "1.2.0"
authors = ["Tronje Krabbe <hi@tron.je>"]
edition = "2021"
license = "0BSD"

[dependencies]
rand = "0.8.5"
clap = { version = "4.1.1", features = ["derive"] }
