[package]
name = "spiceware"
version = "0.1.0"
authors = ["Tronje Krabbe <hi@tron.je>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
clap = { git = "https://github.com/clap-rs/clap.git" }
